import { type Course, type UserProfile } from "./types"

export const courses: Course[] = [
  {
    id: "1",
    title: "Supply Chain Logistics Fundamentals",
    instructor: "Dr. Sarah Chen",
    thumbnail: "/images/course-logistics.jpg",
    pillar: "Logistics",
    progress: 72,
    status: "in-progress",
    totalLessons: 24,
    completedLessons: 17,
    duration: "12 weeks",
    lastAccessed: "2 hours ago",
  },
  {
    id: "2",
    title: "Strategic Procurement & Sourcing",
    instructor: "Prof. James Okafor",
    thumbnail: "/images/course-procurement.jpg",
    pillar: "Procurement",
    progress: 45,
    status: "in-progress",
    totalLessons: 18,
    completedLessons: 8,
    duration: "8 weeks",
    lastAccessed: "1 day ago",
  },
  {
    id: "3",
    title: "Lean Six Sigma Green Belt",
    instructor: "Maria Rodriguez, MBB",
    thumbnail: "/images/course-lean.jpg",
    pillar: "Lean 6 Sigma",
    progress: 100,
    status: "completed",
    totalLessons: 30,
    completedLessons: 30,
    duration: "16 weeks",
    lastAccessed: "1 week ago",
  },
  {
    id: "4",
    title: "Warehouse Management Systems",
    instructor: "David Kim, CSCP",
    thumbnail: "/images/course-warehousing.jpg",
    pillar: "Warehousing",
    progress: 20,
    status: "in-progress",
    totalLessons: 15,
    completedLessons: 3,
    duration: "6 weeks",
    lastAccessed: "3 days ago",
  },
  {
    id: "5",
    title: "Last-Mile Delivery Optimization",
    instructor: "Aisha Patel",
    thumbnail: "/images/course-lastmile.jpg",
    pillar: "Last-Mile",
    progress: 100,
    status: "completed",
    totalLessons: 12,
    completedLessons: 12,
    duration: "4 weeks",
    lastAccessed: "2 weeks ago",
  },
  {
    id: "6",
    title: "Supply Chain Analytics & AI",
    instructor: "Dr. Wei Zhang",
    thumbnail: "/images/course-analytics.jpg",
    pillar: "Analytics",
    progress: 8,
    status: "in-progress",
    totalLessons: 20,
    completedLessons: 2,
    duration: "10 weeks",
    lastAccessed: "5 hours ago",
  },
]

export const userProfile: UserProfile = {
  name: "Alex Nkomo",
  title: "Senior Supply Chain Analyst",
  email: "alex.nkomo@example.com",
  company: "GlobalTech Logistics",
  location: "Johannesburg, South Africa",
  avatarUrl: "",
  bio: "Experienced supply chain professional with 8+ years in logistics optimization and procurement strategy across Sub-Saharan Africa.",
  credentials: [
    {
      name: "APICS CPIM",
      issuer: "ASCM",
      dateEarned: "March 2023",
      status: "active",
    },
    {
      name: "CSCP",
      issuer: "ASCM",
      dateEarned: "November 2022",
      status: "active",
    },
    {
      name: "Lean Six Sigma Green Belt",
      issuer: "ASQ",
      dateEarned: "June 2024",
      status: "active",
    },
  ],
  milestones: [
    {
      title: "Enrolled in Nexus",
      date: "Jan 2022",
      completed: true,
    },
    {
      title: "First Course Completed",
      date: "Apr 2022",
      completed: true,
    },
    {
      title: "CSCP Certification",
      date: "Nov 2022",
      completed: true,
    },
    {
      title: "APICS CPIM Earned",
      date: "Mar 2023",
      completed: true,
    },
    {
      title: "5 Courses Completed",
      date: "Dec 2024",
      completed: false,
    },
    {
      title: "Supply Chain Leader",
      date: "Target 2025",
      completed: false,
    },
  ],
}
